const START_TIMER = "START_TIMER";
const ADD_SECOND = "ADD_SECOND";
const RESTART_TIMER = "RESTART_TIMER";

const ADD_COUNTER = "ADD_COUNTER";
const SUB_COUNTER = "SUB_COUNTER";

export { START_TIMER, ADD_SECOND, RESTART_TIMER, ADD_COUNTER, SUB_COUNTER };
